# Generated by Django 2.1.7 on 2019-09-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20190919_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeimage',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe.Cafe'),
        ),
        migrations.AlterField(
            model_name='cafeimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
