# Generated by Django 2.1.7 on 2019-09-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_auto_20190921_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeimage',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
