# Generated by Django 2.1.7 on 2019-09-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20190921_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='name',
            new_name='title',
        ),
    ]
