# Generated by Django 2.1.7 on 2019-09-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20190922_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeimage',
            name='cafe',
        ),
        migrations.AddField(
            model_name='cafe',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='CafeImage',
        ),
    ]
