# Generated by Django 2.1.7 on 2019-09-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_auto_20190922_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
