# Generated by Django 2.1.7 on 2019-09-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unlike',
            name='user',
        ),
    ]
