# Generated by Django 2.1.7 on 2019-09-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_auto_20190922_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_like',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cafe.Review'),
        ),
        migrations.AlterField(
            model_name='review_unlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unlike', to='cafe.Review'),
        ),
    ]
