# Generated by Django 2.1.7 on 2019-09-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_auto_20190922_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='review',
            name='unlikes_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cafe_unlike',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlike', to='cafe.Cafe'),
        ),
        migrations.AlterField(
            model_name='review_like',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='cafe.Review'),
        ),
        migrations.AlterField(
            model_name='review_unlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlike', to='cafe.Review'),
        ),
    ]
